fix eval getting package name from PKGBUILD if pkgname=-git

diff --git a/cstpkg b/cstpkg
--- a/cstpkg
+++ b/cstpkg
@@ -163,7 +163,8 @@ while [ "$#" -ne "0" ]; do
 			MODIFY=1
 			;;
 		--vimdiff| -v)
-			[[ $(type -p vim) ]] && DIFFCMD="vim -d" || echo 'WARNING: vim was not found' 1>&2
+			[[ $(type -p vim) ]] && DIFFCMD="vim -d" && VERBOSE=1 \
+				|| echo 'WARNING: vim was not found' 1>&2
 			;;
 		--verbose ) 
 			VERBOSE=1 ;;
@@ -177,7 +178,7 @@ if [ ! -r ./PKGBUILD ]; then
 fi
 
 # use eval instead of creating a temp file to get pkgname etc
-eval $(grep -E '^[[:blank:]]*_?(pkg.*|name)=' ./PKGBUILD)
+eval $(grep -E '^[[:blank:]]*_?(pkg.*|git.*|name)=' ./PKGBUILD)
 
 # copy for modification
 cp ./PKGBUILD ./${backupfile}
